language: node_js
node_js:
  - "8.6.0"
services:
  - postgresql
env:
- DATABASE_TEST_URL=postgres://localhost:5432/courtbotdb_test
before_script:
  - psql -c 'create database courtbotdb_test;' -U postgres
  - cp .env.sample .env
  - npm run dbsetup
  - export TZ=America/Anchorage
addons:
  postgresql: "9.6"